class Agenda < ApplicationRecord
  VALIDATES :fecha, PRESENCE: {:MESSAGE => "INGRESE FECHA"}
  VALIDATES :hora, PRESENCE: {:MESSAGE => "INGRESE HORA"}
  VALIDATES :estado, PRESENCE: {:MESSAGE => "INGRESE ESTADO"}
  VALIDATES :descripcion, PRESENCE: {:MESSAGE => "INGRESE DESCRIPCION"}
end
