class Paciente < ApplicationRecord
  VALIDATES :nombres, PRESENCE: {:MESSAGE => "INGRESE NOMBRES"}
  VALIDATES :rut, PRESENCE: {:MESSAGE => "INGRESE RUT"}
  VALIDATES :correo, PRESENCE: {:MESSAGE => "INGRESE CORREO"}
  VALIDATES :direccion, PRESENCE: {:MESSAGE => "INGRESE DIRECCION"}
  VALIDATES :telefono, PRESENCE: {:MESSAGE => "INGRESE TELEFONO"}
end
