class Personal < ApplicationRecord
  VALIDATES :nombres, PRESENCE: {:MESSAGE => "INGRESE NOMBRES"}
  VALIDATES :rut, PRESENCE: {:MESSAGE => "INGRESE RUT"}
  VALIDATES :correo, PRESENCE: {:MESSAGE => "INGRESE CORREO"}
  VALIDATES :telefono, PRESENCE: {:MESSAGE => "INGRESE TELEFONO"}
  VALIDATES :profesion, PRESENCE: {:MESSAGE => "INGRESE PROFESION O CARGO"}
end
