rails g migration addForeignToPacienteAndAgenda
rails g migration addForeignToPersonalAndAgenda
rails g migration addForeignToTratamientoAndAgenda

rails g migration addForeignToGradoAndPersonal

rails g migration addForeignToInsumoAndListado

